version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'hmlsvcrapp'
      MYSQL_USER: 'hmlsvcrapp'
      MYSQL_PASSWORD: 'hmlsvcrapp-password!'
      MYSQL_ROOT_PASSWORD: 'hmlsvcrapp-password!-root'
    volumes:
      - ./createdatabase:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
           python create_superuser.py &&
           python entrypoint.sh
           python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword

volumes:
  mysql_data:
