version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'hmlsvcrapp'
      MYSQL_USER: 'hmlsvcrapp'
      MYSQL_PASSWORD: 'hmlsvcrapp-password!'
      MYSQL_ROOT_PASSWORD: 'hmlsvcrapp-password!-root'
    volumes:
      - mysql_data:/var/lib/mysql
      - /createdatabase.sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  web:
    image: rherbaugh/homelabdatabase:latest
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=adminpassword
    command: >
      sh -c "sleep 60 &&
         python create_superuser.py &&
         python manage.py makemigrations &&
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"

volumes:
  mysql_data: