# Generated by Django 3.2.23 on 2024-01-26 21:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlsvcrapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='associated_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_credentials', to='hmlsvcrapp.server'),
        ),
        migrations.AddField(
            model_name='credential',
            name='associated_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_credentials', to='hmlsvcrapp.service'),
        ),
        migrations.AddField(
            model_name='credential',
            name='cred_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='server',
            name='cred_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='hmlsvcrapp.credential', to_field='cred_name'),
        ),
        migrations.AddField(
            model_name='service',
            name='https_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hmlsvcrapp.network'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='mfa_source',
            field=models.CharField(blank=True, choices=[('Phone', 'Phone'), ('iCloud', 'iCloud Passwords'), ('Bitwarden', 'Bitwarden Passwords'), ('None', 'Not configured/available')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='cloudflare_proxy_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='credentials',
            field=models.ManyToManyField(blank=True, related_name='services', to='hmlsvcrapp.Credential'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dns_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='fqdn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='ldn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='port',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='reverse_proxy_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='wazuh_agent_installed',
            field=models.BooleanField(default=False),
        ),
    ]
