# Generated by Django 3.2.23 on 2024-01-26 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlsvcrapp', '0003_auto_20240126_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmlsvcrapp.credential')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmlsvcrapp.server')),
            ],
            options={
                'unique_together': {('server', 'credential')},
            },
        ),
    ]
