# Generated by Django 3.2.23 on 2024-01-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmlsvcrapp', '0004_servercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cred_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='hmlsvcrapp.credential'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cred_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hmlsvcrapp.credential'),
        ),
    ]
