# Generated by Django 3.2.23 on 2024-01-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmlsvcrapp', '0008_auto_20240126_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Decommissioned', 'Decommissioned')], max_length=50),
        ),
    ]
