name: Docker Image CI

on:
  push:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build adnd Push the Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: rherbaugh/homelabdatabase-dev:latest
